AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for EventBridge Ruleaimlfinalgroup7rule
Resources:
  Rule631b78f6:
    Type: AWS::Events::Rule
    Properties:
      Name: aimlfinalgroup7rule
      EventPattern: >-
        {"source":["aws.glue"],"detail-type":["Glue Crawler State
        Change"],"detail":{"state":["Succeeded"],"crawlerName":["aimlfinalgroup7crawler"]}}
      State: ENABLED
      EventBusName: default
      Targets:
        - Id: Idbc2e52c1-58dc-437f-bb5e-1c4dd0b4cea5
          Arn:
            Fn::Sub: >-
              arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:aimlfinalgroup7lambdagluejob
Parameters: {}
